<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <title>Nightingale Nightmare</title>

        <link rel="stylesheet" href="/css/reveal.css">
        <link rel="stylesheet" href="/css/theme/nightmare.css">

    </head>
    <body>
        <div class="reveal">
            <div class="slides">
                <section>  
                    <h1 class="halloween">Nightingale Nightmare</h1>
                    <img src="/img/white logo.png" class="logo" />
                </section>
                <section data-background-video="video/ben.m4v" data-transition="fade-in slide-out">
                    
                </section>
                <section>  
                    <h1 class="halloween">Nightingale Nightmare</h1>
                    <img src="/img/white logo.png" class="logo" />
                </section>
                <section data-background-video="video/hands.mp4" data-transition="fade-in slide-out">
                    
                </section>
                <section data-transition="zoom-in fade-out">  
                    <h1 class="halloween">Good Luck</h1>
                    <h2 class="halloween">Puny Mortals</h2>
                </section>
            </div>
        </div>

        <script src="/lib/js/head.min.js"></script>
        <script src="/js/reveal.js"></script>

        <script>
            // More info https://github.com/hakimel/reveal.js#configuration
            Reveal.initialize({
                history: true,
                progress: false,
                transition: 'zoom',

                // More info https://github.com/hakimel/reveal.js#dependencies
                dependencies: [
                    { src: '/plugin/markdown/marked.js' },
                    { src: '/plugin/markdown/markdown.js' },
                    { src: '/plugin/notes/notes.js', async: true }
                ]
            });
        </script>
    </body>
</html>