<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

        <title>Nightingale Nightmare</title>
    </head>
    <body>

        <form method="post" action="/photos/tag">

        <?php 
            if (isset($data['photo'])) {
                $photo = $data['photo'];

                echo $photo->get_html_tag();
            ?>

            <?php
            }
        ?>

        <div>
            <label>Bib #
                <input name="bib" type="number" min="1" max="200" autofocus>
            </label>

            <label>Type
                <select name="type" required>
                    <option value=""></option>
                    <option value="mugshot" <?=($data['type']=='mugshot'?'selected':'')?>>Mugshot</option>
                    <option value="fancydress" <?=($data['type']=='fancydress'?'selected':'')?>>Fancy dress</option>
                    <option value="marshal" <?=($data['type']=='marshal'?'selected':'')?>>Marshal</option>
                    <option value="general" <?=($data['type']=='general'?'selected':'')?>>General</option>
                    <option value="runners" <?=($data['type']=='runners'?'selected':'')?>>Runners</option>
                </select>
            </label>
        </div>

        <div>
            <input type="submit" value="Go">
            <input type="hidden" name="photo_id" value="<?=$photo->id?>">
        </div>

        </form>



<style>

body {
    font-family: helvetica, 'sans-serif';
}

img {
    max-width: 100%;
}

form {
    width: 80%;
    margin: 1% auto;
}

form div {
    margin: 20px;
}

label {
    font-size: 32px;
    width: 30%;
}

input, 
select {
    width: 30%;
    font-size: 32px;
    display: inline-block;
}

input[type=submit] {
    width: 200px;
    margin: 0 80px;
    font-size: 32px;
}

.confirm {
    background-color: PaleGreen;
    color: DarkGreen;
    padding: 0.5rem;
    margin: 1rem;
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
}
</style>
    </body>
</html>